# Generated by Django 5.0 on 2023-12-16 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_teammatch_won'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='total_matches_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_matches_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_matches_won',
            field=models.IntegerField(default=0),
        ),
    ]
